package PANTALLAS;

import static PANTALLAS.Pantalla1_JUGAR.frameinstruc;
import javax.swing.*;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Lucia Montoya
 */
public class Pantalla3_MENU extends javax.swing.JFrame {

    private Timer timer;
    private int imageIndex = 0;
    private String[] imagenes;
    private int totalImages;

    public Pantalla3_MENU() {
        initComponents();
        setLocationRelativeTo(null);

        imagenes = new String[]{
            "src/imagenes/5.png",
            "src/imagenes/6.png",
            "src/imagenes/7.png"
        };
        totalImages = imagenes.length;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bt_instrucciones = new javax.swing.JToggleButton();
        Bt_comienzajuego = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_instrucciones.setBorderPainted(false);
        Bt_instrucciones.setContentAreaFilled(false);
        Bt_instrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_instruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 360, 90));

        Bt_comienzajuego.setBorderPainted(false);
        Bt_comienzajuego.setContentAreaFilled(false);
        Bt_comienzajuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_comienzajuegoActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_comienzajuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 360, 90));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxtr\\OneDrive\\Documentos\\GitHub\\LAB_EDD2\\src\\IMAGENES\\Menu.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_instruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_instruccionesActionPerformed
        this.setVisible(false);
        frameinstruc.setVisible(true);
    }//GEN-LAST:event_Bt_instruccionesActionPerformed

    private void Bt_comienzajuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_comienzajuegoActionPerformed
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                ImageIcon icon = new ImageIcon(imagenes[imageIndex]);
                jLabel1.setIcon(icon);
                imageIndex = (imageIndex + 1) % imagenes.length;

                if (imageIndex == 0) {
                    timer.cancel();  // Detener el timer
                    avanzarPantalla();  // Método para avanzar a la nueva pantalla
                }
            }
        }, 0, 15000);

    }//GEN-LAST:event_Bt_comienzajuegoActionPerformed
    private void avanzarPantalla() {
        this.setVisible(false);
        Pantalla4_IMG8 nuevaPantalla = new Pantalla4_IMG8();
        nuevaPantalla.setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla3_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla3_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla3_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla3_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla3_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Bt_comienzajuego;
    private javax.swing.JToggleButton Bt_instrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
